sbatch sbatch_run_one_transcription.sh denver_videos denver_transcribed_files
sbatch sbatch_run_one_transcription.sh durham_videos durham_transcribed_files
sbatch sbatch_run_one_transcription.sh fortworth_videos fortworth_transcribed_files
sbatch sbatch_run_one_transcription.sh jacksonville_videos jacksonville_transcribed_files
sbatch sbatch_run_one_transcription.sh newark_videos newark_transcribed_files
sbatch sbatch_run_one_transcription.sh seattle_videos seattle_transcribed_files